# Julia/JuMP tutorial


## Basic Data Types
Data types are important! It makes Julia faster

Integers

In [2]:
1 + -2

-1

In [3]:
typeof(1)

Int64

Floating point numbers --> computations are more expensive

In [8]:
1.2 - 2.3

-1.0999999999999999

In [9]:
typeof(-1.1)

Float64

Irrational representation of $\pi$ (all the characters are unicode -- type \pi and then press [TAB])

In [7]:
π

π = 3.1415926535897...

In [10]:
typeof(π)

Irrational{:π}

Native support for complex numbers

In [11]:
2 + 3im

2 + 3im

In [12]:
typeof(2.0 + 3im)

ComplexF64 (alias for Complex{Float64})

Doubles quotes are used ofr strings (unicode is OK!)

In [17]:
"This is Julia and this is π"

"This is Julia and this is π"

In [16]:
typeof("This is Julia")

String

# Arithmetic and Equality Testing

In [18]:
1 + 1

2

We can also write things like the following using (\sqrt)

In [19]:
sin(2π/3) == √3/2

false

It should be TRUE! Floating point precision. Let's use \approx instead

In [20]:
sin(2π/3) ≈ √3/2

true

In [21]:
(1 + 1e-16) - 1e-16 == 1 + (1e-16 - 1e-16)

false

## Vectors, Matrices and Arrays

In [22]:
b = [5,6]

2-element Vector{Int64}:
 5
 6

In [23]:
A = [1 2; 3 4]

2×2 Matrix{Int64}:
 1  2
 3  4

In [24]:
x = A\b

2-element Vector{Float64}:
 -3.9999999999999987
  4.499999999999999

In [25]:
A*x

2-element Vector{Float64}:
 5.0
 6.0

In [26]:
A*x == b

true

Dimension matters!

In [27]:
b*b

LoadError: MethodError: no method matching *(::Vector{Int64}, ::Vector{Int64})
Closest candidates are:
  *(::Any, ::Any, ::Any, ::Any...) at operators.jl:591
  *(::StridedMatrix{T}, ::StridedVector{S}) where {T<:Union{Float32, Float64, ComplexF32, ComplexF64}, S<:Real} at C:\Users\MACC-Jose\AppData\Local\Programs\Julia-1.8.5\share\julia\stdlib\v1.8\LinearAlgebra\src\matmul.jl:49
  *(::StridedVecOrMat, ::LinearAlgebra.Adjoint{<:Any, <:LinearAlgebra.LQPackedQ}) at C:\Users\MACC-Jose\AppData\Local\Programs\Julia-1.8.5\share\julia\stdlib\v1.8\LinearAlgebra\src\lq.jl:269
  ...

In [28]:
b*b'

2×2 Matrix{Int64}:
 25  30
 30  36

In [31]:
@show b'*b
@show b*b';

b' * b = 61
b * b' = [25 30; 30 36]


# TUPLES 
immutable collection of values - useful to pass parameters from one place to another - type of a "container" similar to array

In [32]:
t = ("hello",1.2,:foo)

("hello", 1.2, :foo)

In [33]:
typeof(t)

Tuple{String, Float64, Symbol}

In [34]:
t[2]

1.2

You can also unpack them

In [36]:
a, b, c = t
b

1.2

You can give names to the entries, convenient way of making light-weight data structures

In [37]:
t = (word="hello", num=1.2, sym=:foo)

(word = "hello", num = 1.2, sym = :foo)

In [38]:
t.word

"hello"

# Dictionaries

Dictionaries provide a generic way of mapping keys to values

In [39]:
d1 = Dict(1 => "A", 2 => "B", 4 => "D")

Dict{Int64, String} with 3 entries:
  4 => "D"
  2 => "B"
  1 => "A"

In [40]:
d1[2]

"B"

Dictionaries support non-integer and can mix data types

In [41]:
Dict("A" => 1, "B" => 2.5, "D" => 2 - 3im)

Dict{String, Number} with 3 entries:
  "B" => 2.5
  "A" => 1
  "D" => 2-3im

# For loops

In [42]:
for i in 1:5
    println(i)
end

1
2
3
4
5


I can interate over almost anything that is interatable. Note that in contrast to vector languages like Matlab and R, loops do not result in a significant performance degradation in Julia

In [43]:
for i in [1.2, 2.3, 3.4, 4.5, 5.6]
    println(i)
end


1.2
2.3
3.4
4.5
5.6


## Control Flow
Julia control flow is similar to Matlab, using keywords if-elseif-else-end, and the logical operators || and && for 'or' and 'and' respectively

In [48]:
i = 10
for i in 0:3:15
    if i < 5
        println("$(i) is less than 5")
    elseif i < 10
        println("$(i) is less than 10")
    else
        if i == 10
            println("the value is 10")
        else
            println("$(i) is bigger than 10")
        end
    end
end

0 is less than 5
3 is less than 5
6 is less than 10
9 is less than 10
12 is bigger than 10
15 is bigger than 10


## Comprehensions
similar to Python, Julia supports the use of simple loops in the constructions of arrays and dictionaries called comprehensions

In [49]:
[i for i in 1:5]

5-element Vector{Int64}:
 1
 2
 3
 4
 5

Matricies can be built by including multiple indices

In [50]:
[i*j for i in 1:5, j in 5:10]

5×6 Matrix{Int64}:
  5   6   7   8   9  10
 10  12  14  16  18  20
 15  18  21  24  27  30
 20  24  28  32  36  40
 25  30  35  40  45  50

Conditional statements can be used to filter out some values

In [51]:
[i for i in 1:10 if i%2 == 1]

5-element Vector{Int64}:
 1
 3
 5
 7
 9

# Functions

In [52]:
function print_hello()
    println("hello")
end
print_hello()

hello


Adding arguments

In [53]:
function print_it(x) # function takes anything and try to print it
    println(x)
end

print_it("hello")
print_it(1.234)
print_it(:my_id)

hello
1.234
my_id


Optional keyword arguments are also possiblem

In [57]:
function print_it(x; prefix="value") # function takes anything and try to print it
    println("$(prefix) $x")
end

print_it(1.234; prefix="val:")

val: 1.234


The keyword return is used to specify the return values of a function

In [58]:
function mult(x; y=2.0) # adding an optional parameter. Function will assume y is 2 unless we specifically define it
    return x*y
end

mult(4.0)

8.0

In [59]:
mult(4.0, y = 5.0)

20.0

# Mutable vs. immutable objects

Some types in Julia are mutable, which means you can change the values inside them. A good example is an array. You can modify the contents of an array without having to make a new array. 

In contrat, types lik Float64 are immutable. You can modify the contents of a Float64. 

This is something to be aware when passing types into functions. For example:

In [60]:
function mutability_example(mutable_type::Vector{Int}, immutable_type::Int)
    mutable_type[1] += 1
    immutable_type += 1
    return
end

mutable_type = [1,2,3]
immutable_type = 1

mutability_example(mutable_type, immutable_type)

println("mutable_type: $(mutable_type)")
println("immutable_type: $(immutable_type)")

mutable_type: [2, 2, 3]
immutable_type: 1


because Vector{Int} is a mutable type, modifying the variable inside the function changed the value outside the function. In contrast, the change to immutable_type didn't modify the value outside the function

You can check mutability with the isimmutable function

In [62]:
@show isimmutable([1,2,3])
@show isimmutable(1);

isimmutable([1, 2, 3]) = false
isimmutable(1) = true


# Loading Packages

In [63]:
using Random
[rand() for i in 1:10]

10-element Vector{Float64}:
 0.8539349302875219
 0.9854981564805461
 0.9986663731677417
 0.3744413462960945
 0.2752053310736141
 0.5672690150479326
 0.5037508332839404
 0.5202651532472444
 0.4369366319646759
 0.07174670933076877

You can access help mode 

In [65]:
? rand

search: rand randn rand! randn! randexp Random randperm randexp! randperm!



```
rand([rng=GLOBAL_RNG], [S], [dims...])
```

Pick a random element or array of random elements from the set of values specified by `S`; `S` can be

  * an indexable collection (for example `1:9` or `('x', "y", :z)`),
  * an `AbstractDict` or `AbstractSet` object,
  * a string (considered as a collection of characters), or
  * a type: the set of values to pick from is then equivalent to `typemin(S):typemax(S)` for integers (this is not applicable to [`BigInt`](@ref)), to $[0, 1)$ for floating point numbers and to $[0, 1)+i[0, 1)$ for complex floating point numbers;

`S` defaults to [`Float64`](@ref). When only one argument is passed besides the optional `rng` and is a `Tuple`, it is interpreted as a collection of values (`S`) and not as `dims`.

!!! compat "Julia 1.1"
    Support for `S` as a tuple requires at least Julia 1.1.


# Examples

```julia-repl
julia> rand(Int, 2)
2-element Array{Int64,1}:
 1339893410598768192
 1575814717733606317

julia> using Random

julia> rand(MersenneTwister(0), Dict(1=>2, 3=>4))
1=>2

julia> rand((2, 3))
3

julia> rand(Float64, (2, 3))
2×3 Array{Float64,2}:
 0.999717  0.0143835  0.540787
 0.696556  0.783855   0.938235
```

!!! note
    The complexity of `rand(rng, s::Union{AbstractDict,AbstractSet})` is linear in the length of `s`, unless an optimized method with constant complexity is available, which is the case for `Dict`, `Set` and dense `BitSet`s. For more than a few calls, use `rand(rng, collect(s))` instead, or either `rand(rng, Dict(s))` or `rand(rng, Set(s))` as appropriate.

